### ISSUE TITLE
icmp example is using non-existing docker image

### ISSUE THREAD

**Issue by kmjayadeep** [networkservicemesh/examples#96]
In icmp example, simple-endpoint.yaml file is using `networkservicemesh/proxy-sidecar-nse:latest` for the container image. 
But the tag `latest` doesn't exist on docker hub.
Hers is the above mentioned yaml file
https://github.com/networkservicemesh/examples/blob/master/examples/icmp/k8s/simple-endpoint.yaml

I have noticed the same with load balancer example as well.
Can I raise a PR to change it to v0.2.0?

**Comment by kmjayadeep** [comment]
here is the dockerhub link https://hub.docker.com/r/networkservicemesh/proxy-sidecar-nse/tags

**Comment by edwarnicke** [comment]
@kmjayadeep You are correct... the good news is that @latest in this case should be the same as @v.0.2.0 ... I believe I've fixed it now :)

https://hub.docker.com/r/networkservicemesh/proxy-sidecar-nse/tags

**Comment by kmjayadeep** [comment]
@edwarnicke thanks. The example should be working now :)
